package FormCreator.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int DropDownField = 0;
  public static final int DropDownLabel = 1;
  public static final int Form = 2;
  public static final int FormFields = 3;
  public static final int TextField = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x4bffbe94391444b5L, 0x854ab80f4a103b67L);
    builder.put(0x56f245f870d44e8cL, DropDownField);
    builder.put(0x56f245f870d6a78cL, DropDownLabel);
    builder.put(0x56f245f870d44e7aL, Form);
    builder.put(0x56f245f870d44e87L, FormFields);
    builder.put(0x56f245f870d44e8bL, TextField);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
