package FormCreator.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptDropDownField = createDescriptorForDropDownField();
  /*package*/ final ConceptDescriptor myConceptDropDownLabel = createDescriptorForDropDownLabel();
  /*package*/ final ConceptDescriptor myConceptForm = createDescriptorForForm();
  /*package*/ final ConceptDescriptor myConceptFormFields = createDescriptorForFormFields();
  /*package*/ final ConceptDescriptor myConceptTextField = createDescriptorForTextField();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptDropDownField, myConceptDropDownLabel, myConceptForm, myConceptFormFields, myConceptTextField);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.DropDownField:
        return myConceptDropDownField;
      case LanguageConceptSwitch.DropDownLabel:
        return myConceptDropDownLabel;
      case LanguageConceptSwitch.Form:
        return myConceptForm;
      case LanguageConceptSwitch.FormFields:
        return myConceptFormFields;
      case LanguageConceptSwitch.TextField:
        return myConceptTextField;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForDropDownField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FormCreator", "DropDownField", 0x4bffbe94391444b5L, 0x854ab80f4a103b67L, 0x56f245f870d44e8cL);
    b.class_(false, false, false);
    b.super_("FormCreator.structure.FormFields", 0x4bffbe94391444b5L, 0x854ab80f4a103b67L, 0x56f245f870d44e87L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:8c13d0af-8195-4aac-b44d-4911d5311095(FormCreator.structure)/6265146964972949132");
    b.version(2);
    b.aggregate("label", 0x56f245f870d6a7e6L).target(0x4bffbe94391444b5L, 0x854ab80f4a103b67L, 0x56f245f870d6a78cL).optional(false).ordered(true).multiple(true).origin("6265146964973103078").done();
    b.alias("dropdown");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDropDownLabel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FormCreator", "DropDownLabel", 0x4bffbe94391444b5L, 0x854ab80f4a103b67L, 0x56f245f870d6a78cL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:8c13d0af-8195-4aac-b44d-4911d5311095(FormCreator.structure)/6265146964973102988");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForForm() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FormCreator", "Form", 0x4bffbe94391444b5L, 0x854ab80f4a103b67L, 0x56f245f870d44e7aL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:8c13d0af-8195-4aac-b44d-4911d5311095(FormCreator.structure)/6265146964972949114");
    b.version(2);
    b.aggregate("formFields", 0x56f245f870d44e81L).target(0x4bffbe94391444b5L, 0x854ab80f4a103b67L, 0x56f245f870d44e87L).optional(false).ordered(true).multiple(true).origin("6265146964972949121").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFormFields() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FormCreator", "FormFields", 0x4bffbe94391444b5L, 0x854ab80f4a103b67L, 0x56f245f870d44e87L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:8c13d0af-8195-4aac-b44d-4911d5311095(FormCreator.structure)/6265146964972949127");
    b.version(2);
    b.prop("dbName", 0x6bdab20123274f1cL, "7771719824935702300");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTextField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("FormCreator", "TextField", 0x4bffbe94391444b5L, 0x854ab80f4a103b67L, 0x56f245f870d44e8bL);
    b.class_(false, false, false);
    b.super_("FormCreator.structure.FormFields", 0x4bffbe94391444b5L, 0x854ab80f4a103b67L, 0x56f245f870d44e87L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:8c13d0af-8195-4aac-b44d-4911d5311095(FormCreator.structure)/6265146964972949131");
    b.version(2);
    b.alias("text");
    return b.create();
  }
}
