package FormCreator.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new DropDownField_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new DropDownLabel_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Form_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new FormFields_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new TextField_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x4bffbe94391444b5L, 0x854ab80f4a103b67L, 0x56f245f870d44e8cL), MetaIdFactory.conceptId(0x4bffbe94391444b5L, 0x854ab80f4a103b67L, 0x56f245f870d6a78cL), MetaIdFactory.conceptId(0x4bffbe94391444b5L, 0x854ab80f4a103b67L, 0x56f245f870d44e7aL), MetaIdFactory.conceptId(0x4bffbe94391444b5L, 0x854ab80f4a103b67L, 0x56f245f870d44e87L), MetaIdFactory.conceptId(0x4bffbe94391444b5L, 0x854ab80f4a103b67L, 0x56f245f870d44e8bL)).seal();
}
