package XMLJava.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int TestElement = 0;
  public static final int VarElementRef = 1;
  public static final int VarXmlElement = 2;
  public static final int XMLExpr = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xab66041823a64c26L, 0xa8fc9db16a81fe77L);
    builder.put(0x70ab13ed8c38f1bL, TestElement);
    builder.put(0x70ab13ed8ab4340L, VarElementRef);
    builder.put(0x70ab13ed8aaae6eL, VarXmlElement);
    builder.put(0x5f7e1db3e89dce86L, XMLExpr);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
