package ModelExample;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.LinkedHashMap;
import java.util.Map;
import java.sql.Statement;
import java.sql.SQLException;
import java.awt.GridLayout;
import javax.swing.JLabel;
import java.awt.List;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.SwingUtilities;

public class Application extends JFrame {

  private JTextField textField_a = new JTextField();
  private JTextField textField_b = new JTextField();
  private JTextField textField_c = new JTextField();
  private JComboBox dropDownField_d;

  private void save() {
    // create connection 
    String dbName = "Application";
    String url = "jdbc:sqlite:./" + dbName;
    Connection connection;
    try {
      connection = DriverManager.getConnection(url);
      String tablename = "Application";
      // get data 
      LinkedHashMap<String, String> data = new LinkedHashMap();
      data.put("firstName", textField_a.getText());
      data.put("lastName", textField_b.getText());
      data.put("age", textField_c.getText());
      data.put("university", dropDownField_d.getSelectedItem().toString());

      String table = "CREATE TABLE IF NOT EXISTS " + tablename + " (\n id integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n";
      String insert = "INSERT INTO " + tablename;
      String column = "(";
      String values = "(";
      int i = 0;
      for (Map.Entry<String, String> element : data.entrySet()) {
        table += " " + element.getKey() + " text NOT NULL";
        column += element.getKey();
        values += "'" + element.getValue() + "'";
        if (++i < data.entrySet().size()) {
          column += ",";
          values += ",";
          table += ",";
        }
        table += "\n";
      }
      table += ");";
      insert += column + ") VALUES" + values + ")";
      Statement stmt = connection.createStatement();
      stmt.execute(table);
      stmt.execute(insert);
    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  public Application() {
    setTitle("Application");
    setLayout(new GridLayout(0, 2));

    add(new JLabel("First Name"));
    add(textField_a);

    add(new JLabel("Last Name"));
    add(textField_b);

    add(new JLabel("Age"));
    add(textField_c);

    {
      List labels = new List();
      labels.add("Lappenanta university of technology");
      labels.add("Universität Koblenz-Landau");
      dropDownField_d = new JComboBox(labels.getItems());
      add(new JLabel("University"));
      add(dropDownField_d);
    }
    JButton submitButton = new JButton("Save");
    submitButton.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent p0) {
        save();
      }
    });
    add(submitButton);
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    pack();
    setVisible(true);
  }

  public static void main(String[] args) {
    SwingUtilities.invokeLater(new Runnable() {
      public void run() {
        new Application();
      }
    });
  }
}
