package FormCreator.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.LinkedHashMap;
import java.util.Map;
import java.sql.Statement;
import java.sql.SQLException;
import java.awt.GridLayout;
import javax.swing.JLabel;
import java.awt.List;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.SwingUtilities;

public class Umfrage extends JFrame {

  private JTextField textField_a_0 = new JTextField();
  private JTextField textField_b_0 = new JTextField();
  private JTextField textField_d = new JTextField();
  private JComboBox dropDownField_c_0;
  private JComboBox dropDownField_e;

  private void save() {
    // create connection 
    String dbName = "Umfrage";
    String url = "jdbc:sqlite:./" + dbName;
    Connection connection;
    try {
      connection = DriverManager.getConnection(url);
      String tablename = "Umfrage";
      // get data 
      LinkedHashMap<String, String> data = new LinkedHashMap();
      data.put("", textField_a_0.getText());
      data.put("", textField_b_0.getText());
      data.put("", dropDownField_c_0.getSelectedItem().toString());
      data.put("", textField_d.getText());
      data.put("", dropDownField_e.getSelectedItem().toString());

      String table = "CREATE TABLE IF NOT EXISTS " + tablename + " (\n id integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n";
      String insert = "INSERT INTO " + tablename;
      String column = "(";
      String values = "(";
      int i = 0;
      for (Map.Entry<String, String> element : data.entrySet()) {
        table += " " + element.getKey() + " text NOT NULL";
        column += element.getKey();
        values += "'" + element.getValue() + "'";
        if (++i < data.entrySet().size()) {
          column += ",";
          values += ",";
          table += ",";
        }
        table += "\n";
      }
      table += ");";
      insert += column + ") VALUES" + values + ")";
      Statement stmt = connection.createStatement();
      stmt.execute(table);
      stmt.execute(insert);
    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  public Umfrage() {
    setTitle("Umfrage");
    setLayout(new GridLayout(0, 2));

    add(new JLabel("Name"));
    add(textField_a_0);

    add(new JLabel("Studiengang"));
    add(textField_b_0);

    add(new JLabel("Anmerkungen"));
    add(textField_d);

    {
      List labels = new List();
      labels.add("Fisch");
      labels.add("Pommes");
      labels.add("Nudeln");
      dropDownField_c_0 = new JComboBox(labels.getItems());
      add(new JLabel("Lieblingsessen"));
      add(dropDownField_c_0);
    }
    {
      List labels = new List();
      labels.add("nein");
      labels.add("ja");
      dropDownField_e = new JComboBox(labels.getItems());
      add(new JLabel("Geheim"));
      add(dropDownField_e);
    }
    JButton submitButton = new JButton("Save");
    submitButton.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent p0) {
        save();
      }
    });
    add(submitButton);
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    pack();
    setVisible(true);
  }

  public static void main(String[] args) {
    SwingUtilities.invokeLater(new Runnable() {
      public void run() {
        new Umfrage();
      }
    });
  }
}
